AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  SwiftToolchainUrl:
    Type: String

Mappings:
  ImageMap:
    us-east-1:
      HVM: ami-0323c3dd2da7fb37d
    us-east-2: 
      HVM: ami-0f7919c33c90f5b58
    us-west-1: 
      HVM: ami-06fcc1f0bc2c8943f
    us-west-2: 
      HVM: ami-0d6621c01e8c2de2c
    ap-south-1: 
      HVM: ami-0470e33cd681b2476
    ap-northeast-1: 
      HVM: ami-0f310fced6141e627
    ap-northeast-2: 
      HVM: ami-01288945bd24ed49a
    ap-southeast-1: 
      HVM: ami-0ec225b5e01ccb706
    ap-southeast-2: 
      HVM: ami-0970010f37c4f9c8d
    ca-central-1: 
      HVM: ami-054362537f5132ce2
    eu-central-1: 
      HVM: ami-076431be05aaf8080
    eu-west-1: 
      HVM: ami-06ce3edf0cff21f07
    eu-west-2: 
      HVM: ami-01a6e31ac994bbc09
    eu-west-3: 
      HVM: ami-00077e3fed5089981
    eu-north-1: 
      HVM: ami-0b7a46b4bd694e8a6
    sa-east-1:
      HVM: ami-003449ffb2605a74c

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./vpc.yml
      Parameters: 
        SwiftToolchainUrl: !Ref SwiftToolchainUrl
        ImageId : !FindInMap
          - ImageMap
          - !Ref 'AWS::Region'
          - "HVM"

  Pipeline:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./pipeline.yml
      Parameters: 
        WebAppASG: !GetAtt VPC.Outputs.WebAppASG

Outputs:
  Ec2LbUrl:
    Value: !GetAtt VPC.Outputs.Ec2LbUrl
  S3ArtifactBucket:
    Value: !GetAtt Pipeline.Outputs.ArtifactStoreS3Location
  CodeBuildImage:
    Value: !GetAtt Pipeline.Outputs.CodeBuildImage